# Generated by Django 3.2.15 on 2022-11-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=80)),
                ('nickname', models.CharField(blank=True, max_length=80)),
                ('bio', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50)),
                ('create_at', models.DateTimeField(auto_created=True)),
            ],
        ),
    ]
