# Generated by Django 3.2.15 on 2022-11-19 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=80, unique=True, verbose_name='Username')),
                ('nickname', models.CharField(max_length=80, verbose_name='Nickname')),
                ('bio', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.CharField(blank=True, max_length=200)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.users', verbose_name="User's id")),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
